### PR TITLE
Implement ROS control example

### PR DESCRIPTION
**Pull request by lukicdarkoo**
This PR follows changes in https://github.com/cyberbotics/webots/pull/2822

---

Note to me.

Add:
```
rosrun teleop_twist_keyboard teleop_twist_keyboard.py cmd_vel:=/pioneer_diff_drive_controller/cmd_vel
```
to http://wiki.ros.org/webots_ros/Tutorials/Sample%20Simulations

### CODE REVIEW

**Review by omichel — COMMENTED** [review]
It looks good. But I don't like very much having a Pioneer3at_ENU proto which is a copy of the original proto simply rotated, I guess. First of all, the term ENU seems wrong, I would call it FLU (X-Forward, Y-Left, Z-Up) and I am wondering how we could avoid code redundancy. Maybe using the `coordiante_system` variable from the WorldInfo as explained here: https://cyberbotics.com/doc/reference/procedural-proto-nodes to automatically rotate the proto if in a ENU world as we do it here:

https://github.com/cyberbotics/webots/blob/8081dbbc1b30dc671f4fa0ad4f88ec46e5fd6a97/projects/objects/backgrounds/protos/TexturedBackgroundLight.proto#L105-L107

What do you think?

**Comment by lukicdarkoo** [comment]
> It looks good. But I don't like very much having a Pioneer3at_ENU proto which is a copy of the original proto simply rotated, I guess. First of all, the term ENU seems wrong, I would call it FLU (X-Forward, Y-Left, Z-Up) and I am wondering how we could avoid code redundancy. 

Creating a new proto (`proto_name_ENU.proto`) looks ugly and I would like to avoid it. We did it a lot in `webots_ros2` and it generates a lot of code that may cause confusion. We need to make the examples simple and clean.

However, I am not sure what is the best way to solve the problem.

> Maybe using the `coordiante_system` variable from the WorldInfo as explained here: https://cyberbotics.com/doc/reference/procedural-proto-nodes to automatically rotate the proto if in a ENU world as we do it here:
> 
> https://github.com/cyberbotics/webots/blob/8081dbbc1b30dc671f4fa0ad4f88ec46e5fd6a97/projects/objects/backgrounds/protos/TexturedBackgroundLight.proto#L105-L107

We can have a non-FLU robot in the ENU coordinate system. It's a bit weird to change the pose of the robot's internal components depending on the coordinate system. What about adding a new parameter to the PROTO?

**Comment by omichel** [comment]
> We can have a non-FLU robot in the ENU coordinate system. It's a bit weird to change the pose of the robot's internal components depending on the coordinate system. What about adding a new parameter to the PROTO?

Yes, I like the idea of adding a FLU boolean parameter to the robot.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
