### PR TITLE
Add camera recognition segmentation in complete_test

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Followup of https://github.com/cyberbotics/webots/pull/2199 and https://github.com/cyberbotics/webots/pull/2431: test the camera segmentation functionality in ROS `complete_test`.

### CODE REVIEW

**Comment by omichel** [comment]
What is the status of this PR?

**Comment by stefaniapedrazzi** [comment]
I will test and complete it

**Comment by stefaniapedrazzi** [comment]
The changes in this branch are working correctly.
But I'm still checking because on my system the ROS `complete_test` blocks at the end of the Camera / beginning of DistanceSensor tests (same occurs also on the develop branch).

**Comment by stefaniapedrazzi** [comment]
The issue comes from the InterialUnit tests and it is not related to Camera.
So it would be better to fix it in a separate PR.

**Comment by stefaniapedrazzi** [comment]
I will now check and fix the issue with InertialUnit.

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
