### PR TITLE
Add Tiago example

### PR DESCRIPTION
**Pull request by lukicdarkoo**
This PR adds a Tiago example which integrates:
- ros_control,
- differential drive,
- mapping capabilities, and
- MoveIt.

image

Commands:
```
rosrun teleop_twist_keyboard teleop_twist_keyboard.py cmd_vel:=/diff_drive_controller/cmd_vel
rosrun gmapping slam_gmapping scan:=/tiago/Hokuyo_URG_04LX_UG01/laser_scan/layer0 _xmax:=5 _xmin:=-5 _ymax:=5 _ymin:=-5 _delta:=0.1
```

### CODE REVIEW

**Comment by lukicdarkoo** [comment]
https://user-images.githubusercontent.com/2135826/110548871-87ffc900-8131-11eb-917a-b40286e6b4e4.mp4
(the new ROS controller works with MoveIt without changes)

MoveIt with Tiago works nicely, but I am not sure where to put MoveIt+Tiago config and launch files. There are a lot of them (generated using MoveIt wizard) and I would not like to pollute this package.

**Comment by omichel** [comment]
Cant' we put all these configuration files into a folder, so that it doesn't look too ugly?

**Comment by lukicdarkoo** [comment]
I am not sure, I think we have to put it in a separate package, like `webots_ros_tiago`

**Comment by lukicdarkoo** [comment]
I managed somehow to include 15+ configuration files generated by the MoveIt Setup Assistant into the single launch file and SRDF file. Now it is easier to distribute.

In general, we should use an official MoveIt configuration for a robot, but since the latest supported version of the Tiago package targets Melodic we are making a compromise here.

**Review by omichel — APPROVED** [review]

**Pull request merged**
