### PR TITLE
Merge develop into master branch

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
Synchronize branches to prepare for the Webots release.

### CODE REVIEW

**Comment by ygoumaz** [comment]
Once the merge is done, we can update the submodule on the Webots side (master and develop branch) and launch test_ros to make sure everything works correctly. Once R2023b is released, we can also release 2023.1.0

**Review by ygoumaz — CHANGES_REQUESTED** [review]
I would update the version number in all world file before merging the sync. Or we could also do it after for both master and develop.

**Comment by stefaniapedrazzi** [comment]
I would do it in a separate PR, given that this one doesn't have a branch.

**Review by ygoumaz — APPROVED** [review]
Thank you!

**Pull request merged**
