### PR TITLE
Fix InterialUnit service name

### PR DESCRIPTION
**Pull request by stefaniapedrazzi**
This change is required to be compatible with Webots R2021a.
I'm merging it directly in the `master` branch that after #44 will contain the code compatible with R2021a.

### CODE REVIEW

**Review by omichel — APPROVED** [review]
Thank you.

**Comment by lukicdarkoo** [comment]
A bug like this should be reported by CI? Do you have an idea what happened?

**Comment by stefaniapedrazzi** [comment]
With this bug the controller doesn't fail but never ends.
I can inspect if we already have a timeout mechanism to detect failures in ROS test.

**Comment by lukicdarkoo** [comment]
@stefaniapedrazzi Created an issue:
https://github.com/cyberbotics/webots_ros/issues/47

**Pull request merged**
