### PR TITLE
Feature worlds using extern proto

### PR DESCRIPTION
**Pull request by carikaser**
Using EXTERNPROTOs in the webots_ros world files

### CODE REVIEW

**Comment by ad-daniel** [comment]
There seems to be a conflict, is this PR ready for review or should it be changed to draft?

**Comment by ygoumaz** [comment]
This branch needs to be re-based to `master` to be included in the next release.

**Review by ygoumaz — CHANGES_REQUESTED** [review]

**Review by ad-daniel — APPROVED** [review]
Thank you. On the ROS side, do we have already a mechanism that converts the webots:// urls to the `https://raw.github.../R2022b` prior to creating the package?

**Comment by ad-daniel** [comment]
@ygoumaz

**Comment by ygoumaz** [comment]
Not that I am aware of. I'll look into that and, if not, I'll implement it before creating the package.

**Pull request merged**
