### PR TITLE
Merge master into develop

### PR DESCRIPTION
**Pull request by lukicdarkoo**
There were no conflicts, but #80 got ignored

### CODE REVIEW

**Comment by omichel** [comment]
It seems that the skin stuff was removed after #80 was merged into develop which explains why we lost it temporarily: https://github.com/cyberbotics/webots_ros/commit/1029667ca9b015db6b90213ad69607e09faeb010

**Review by BenjaminHug8 — APPROVED** [review]
Thank you.

**Review by BenjaminHug8 — CHANGES_REQUESTED** [review]
It seems we do not have gps_speed_vector, let me check.

**Comment by BenjaminHug8** [comment]
It seems I changed a targeted branch for this [PR](https://github.com/cyberbotics/webots_ros/pull/85/commits/69b2f723928ba8acf79f35207b853007eb0a95b2) and the skin stuff and the gps speed vector have been removed with this.

I pushed a commit to add again the test with gps speed vector.

Let me know if it seems good also for you @lukicdarkoo.

**Comment by lukicdarkoo** [comment]
f247b1b deleted gps_speed test, I re-added it in 293a3dc

**Review by BenjaminHug8 — APPROVED** [review]
Thank you!

**Pull request merged**
